// icons from https://lucide.dev
import {
  Bolt,
  ShoppingBag,
  BellDot,
  BookOpenText,
  BriefcaseBusiness,
  CircleHelp,
  TriangleAlert,
  Users,
  Lock,
  Dessert,
  ShieldPlus,
  MessageCircle,
  Figma,
  Play,
  MapPin,
  Database,
  PanelsTopLeft,
  PanelTop,
} from "lucide-react";

// Menu data
export const Menus = [
  {
    name: "Luces Led",
    subMenuHeading: ["Focos", "Varios"],
    subMenu: [
      {
        name: "Delanteros",
        desc: "",
        icon: PanelsTopLeft,
        pos: "1101",
      },
      {
        name: "Balizas",
        desc: "",
        icon: ShoppingBag,
        pos: "1201",
      },
      {
        name: "Traseros",
        desc: "",
        icon: Bolt,
        pos: "1102",
      },
      {
        name: "Bases metálicas",
        desc: "",
        icon: MapPin,
        pos: "1203",
      },
      {
        name: "Laterales",
        desc: "",
        icon: PanelTop,
        pos: "1103",
      },
      {
        name: "Estroboscópicos",
        desc: "",
        icon: BellDot,
        pos: "1204",
      },
      {
        name: "Faeneros",
        desc: "",
        icon: Database,
        pos: "1104",
      },
      {
        name: "Micas",
        desc: "",
        icon: Play,
        pos: "1205",
      },
    ],
    gridCols: 2,
  },
  {
    name: "Artículos Eléctricos",
    subMenuHeading: ["", ""],
    subMenu: [
      {
        name: "Cables",
        desc: "",
        icon: ShoppingBag,
        pos: "2001",
      },
      {
        name: "Enchufes",
        desc: "",
        icon: MapPin,
        pos: "2002",
      },
      {
        name: "Ampolletas",
        desc: "",
        icon: BellDot,
        pos: "2003",
      },
      {
        name: "Terminales de batería",
        desc: "",
        icon: Play,
        pos: "2004",
      },
      {
        name: "Fusibles",
        desc: "",
        icon: BookOpenText,
        pos: "2005",
      },
      {
        name: "Varios",
        desc: "",
        icon: Figma,
      },
    ],
    gridCols: 2,
  },
  {
    name: "Accesorios",
    subMenu: [
      {
        name: "Adornos",
        desc: "",
        icon: CircleHelp,
        pos: "3001",
      },
      {
        name: "Antenas",
        desc: "",
        icon: MessageCircle,
        pos: "3002",
      },
      {
        name: "Bocinas",
        desc: "",
        icon: TriangleAlert,
        pos: "3003",
      },
      {
        name: "Espejos",
        desc: "",
        icon: ShoppingBag,
        pos: "3004",
      },
      {
        name: "Guardafangos",
        desc: "",
        icon: MapPin,
        pos: "3005",
      },
      {
        name: "Herramientas",
        desc: "",
        icon: BellDot,
        pos: "3006",
      },
      {
        name: "Plumillas",
        desc: "",
        icon: Play,
        pos: "3007",
      },
      {
        name: "Tapas y cubretuercas",
        desc: "",
        icon: BookOpenText,
        pos: "3008",
      },
      {
        name: "Tubos de escape",
        desc: "",
        icon: Figma,
        pos: "3009",
      },
      {
        name: "Piezas de arrastre",
        desc: "",
        icon: PanelsTopLeft,
        pos: "3010",
      },
      {
        name: "Eslingas y accesorios",
        desc: "",
        icon: ShoppingBag,
        pos: "3011",
      },
      {
        name: "Varios",
        desc: "",
        icon: Bolt,
        pos: "3012",
      },
    ],
    gridCols: 2,
  },
  {
    name: "Niples y mangueras",
    subMenuHeading: ["", "", ""],
    subMenu: [
      {
        name: "Unión Tubos plast.",
        desc: "",
        icon: ShieldPlus,
        pos: "4101",
      },
      {
        name: "Conector c/hilo plast.",
        desc: "",
        icon: Users,
        pos: "4102",
      },
      {
        name: "Tee e Y plast.",
        desc: "",
        icon: Dessert,
        pos: "4103",
      },
      {
        name: "Unión Tubos bronce",
        desc: "",
        icon: Lock,
        pos: "4201",
      },
      {
        name: "Conector c/hilo bronce",
        desc: "",
        icon: CircleHelp,
        pos: "4202",
      },
      {
        name: "Tee bronce",
        desc: "",
        icon: MessageCircle,
        pos: "4203",
      },
      {
        name: "Unión mangueras",
        desc: "",
        icon: TriangleAlert,
        pos: "4301",
      },
      {
        name: "Espiga c/hilo",
        desc: "",
        icon: ShoppingBag,
        pos: "4302",
      },
      {
        name: "Tee espiga",
        desc: "",
        icon: MapPin,
        pos: "4303",
      },
      {
        name: "Adaptador HI-HI",
        desc: "",
        icon: BellDot,
        pos: "4501",
      },
      {
        name: "Adaptador HE-HE",
        desc: "",
        icon: Play,
        pos: "4502",
      },
      {
        name: "Adaptador HI-HE",
        desc: "",
        icon: BookOpenText,
        pos: "4503",
      },
      {
        name: "Tee HI",
        desc: "",
        icon: Figma,
        pos: "4504",
      },
      {
        name: "Acoples rápidos",
        desc: "",
        icon: PanelsTopLeft,
        pos: "4601",
      },
      {
        name: "Racor y Banjos",
        desc: "",
        icon: ShoppingBag,
        pos: "4602",
      },
      {
        name: "Tapones",
        desc: "",
        icon: Bolt,
        pos: "4603",
      },
      {
        name: "Pasamuros",
        desc: "",
        icon: Figma,
        pos: "4604",
      },
    ],
    gridCols: 3,
  },
  {
    name: "Frenos de Aire",
    subMenuHeading: ["", ""],
    subMenu: [
      {
        name: "Pulmones de freno",
        desc: "",
        icon: CircleHelp,
        pos: "5001",
      },
      {
        name: "Tambores, masas y accesorios",
        desc: "",
        icon: Bolt,
        pos: "5002",
      },
      {
        name: "Chicharras",
        desc: "",
        icon: ShoppingBag,
        pos: "5003",
      },
      {
        name: "Ejes de leva y bujes",
        desc: "",
        icon: ShieldPlus,
        pos: "5004",
      },
      {
        name: "Reparación de frenos",
        desc: "",
        icon: BookOpenText,
        pos: "5005",
      },
      {
        name: "Manos de acople",
        desc: "",
        icon: Database,
        pos: "5006",
      },
    ],
    gridCols: 2,
  },
  {
    name: "Válvulas de Aire",
    subMenuHeading: ["", ""],
    subMenu: [
      {
        name: "Gobernadores",
        desc: "",
        icon: CircleHelp,
      },
      {
        name: "Relays",
        desc: "",
        icon: Bolt,
      },
      {
        name: "Pedaleras",
        desc: "",
        icon: ShieldPlus,
      },
      {
        name: "Seguridad",
        desc: "",
        icon: BookOpenText,
      },
      {
        name: "Solenoides",
        desc: "",
        icon: TriangleAlert,
      },
      {
        name: "Acción Maxi",
        desc: "",
        icon: CircleHelp,
      },
      {
        name: "Retención - Check",
        desc: "",
        icon: BriefcaseBusiness,
      },
      {
        name: "Descargas rápidas",
        desc: "",
        icon: BellDot,
      },
    ],
    gridCols: 2,
  },
  {
    name: "Suspensión",
    subMenuHeading: ["", ""],
    subMenu: [
      {
        name: "Balancines",
        desc: "",
        icon: CircleHelp,
      },
      {
        name: "Tensores",
        desc: "",
        icon: BriefcaseBusiness,
      },
      {
        name: "Torres",
        desc: "",
        icon: BookOpenText,
      },
      {
        name: "Manos",
        desc: "",
        icon: BellDot,
      },
      {
        name: "Fuelles",
        desc: "",
        icon: ShoppingBag,
      },
      {
        name: "Bujes",
        desc: "",
        icon: Bolt,
      },
      {
        name: "Válvulas",
        desc: "",
        icon: CircleHelp,
      },
    ],
    gridCols: 2,
  },
];
